import React, { forwardRef } from 'react';

const AssessmentReport = forwardRef(({ results }, ref) => {
    if (!results) return null;

    const getScoreColor = (score) => {
        if (score >= 80) return 'text-green-600';
        if (score >= 60) return 'text-yellow-600';
        return 'text-red-600';
    };

    return (
        <div ref={ref} className="bg-white p-10 max-w-[210mm] mx-auto text-gray-900 font-sans" style={{ width: '210mm', minHeight: '297mm' }}>
            {/* Header */}
            <div className="border-b-2 border-gray-100 pb-6 mb-8 flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-black text-primary mb-2">Interview Readiness Report</h1>
                    <p className="text-gray-500 text-sm">Generated by AI PrepPulse • {new Date().toLocaleDateString()}</p>
                </div>
                <div className="text-right">
                    <div className="text-5xl font-black text-gray-900">{results.overallScore}</div>
                    <div className="text-xs font-bold uppercase tracking-wider text-gray-500">Overall Score</div>
                </div>
            </div>

            {/* Section 1: Theory / Methodology */}
            <div className="mb-10 bg-gray-50 rounded-xl p-6 border border-gray-100">
                <h2 className="text-lg font-bold text-gray-900 uppercase tracking-wider mb-3 flex items-center gap-2">
                    <span className="material-symbols-outlined text-primary">school</span>
                    Methodology
                </h2>
                <p className="text-gray-700 text-sm leading-relaxed text-justify">
                    PROPRIETARY ASSESSMENT MODEL: This report is generated using our advanced AI analysis engine, which evaluates candidate readiness across four critical pillars:
                    <strong> Technical Proficiency</strong> (coding depth and problem-solving),
                    <strong> Resume Impact</strong> (ATS compatibility and narrative strength),
                    <strong> Communication</strong> (clarity and structure), and
                    <strong> Portfolio Quality</strong> (demonstrable proof of work).
                    This holistic approach provides a 360-degree view of your current interview standing and predicts potential success in competitive hiring processes.
                </p>
            </div>

            {/* Section 2: Executive Summary */}
            <div className="mb-10">
                <h2 className="text-lg font-bold text-gray-900 uppercase tracking-wider mb-4 flex items-center gap-2">
                    <span className="material-symbols-outlined text-purple-600">analytics</span>
                    Executive Summary
                </h2>
                <div className="p-6 rounded-xl border-l-4 border-purple-500 bg-purple-50">
                    <p className="text-gray-800 text-lg font-medium italic mb-4">
                        "{results.motivationalMessage}"
                    </p>
                    <div className="grid grid-cols-2 gap-4 mt-4">
                        <div>
                            <span className="text-xs font-bold text-gray-500 uppercase">Current Status</span>
                            <div className="text-xl font-black text-gray-900">{results.readinessLevel}</div>
                        </div>
                        <div>
                            <span className="text-xs font-bold text-gray-500 uppercase">Est. Preparation Time</span>
                            <div className="text-xl font-bold text-gray-900">{results.timeline.weeks} Weeks</div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Section 3: Visuals / Category Breakdown */}
            <div className="mb-10">
                <h2 className="text-lg font-bold text-gray-900 uppercase tracking-wider mb-6 flex items-center gap-2">
                    <span className="material-symbols-outlined text-blue-600">bar_chart</span>
                    Performance Visualization
                </h2>

                <div className="grid grid-cols-2 gap-x-12 gap-y-8">
                    {Object.entries(results.categoryScores).map(([category, score]) => (
                        <div key={category}>
                            <div className="flex justify-between items-end mb-2">
                                <span className="capitalize font-bold text-gray-700">{category}</span>
                                <span className={`font-black ${getScoreColor(score)}`}>{score}/100</span>
                            </div>
                            <div className="h-3 bg-gray-100 rounded-full overflow-hidden">
                                <div
                                    className={`h-full rounded-full ${score >= 80 ? 'bg-green-500' : score >= 60 ? 'bg-yellow-500' : 'bg-red-500'}`}
                                    style={{ width: `${score}%` }}
                                ></div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Section 4: Key Insights */}
            <div className="grid grid-cols-2 gap-8">
                <div>
                    <h3 className="font-bold text-gray-900 mb-4 border-b pb-2">Top Strengths</h3>
                    <ul className="space-y-2">
                        {results.strengths.slice(0, 4).map((strength, i) => (
                            <li key={i} className="text-sm text-gray-600 flex items-start gap-2">
                                <span className="text-green-500 font-bold">•</span>
                                {strength}
                            </li>
                        ))}
                    </ul>
                </div>
                <div>
                    <h3 className="font-bold text-gray-900 mb-4 border-b pb-2">Critical Focus Areas</h3>
                    <ul className="space-y-2">
                        {results.categoryDetails && Object.values(results.categoryDetails)
                            .flatMap(d => d.weaknesses)
                            .slice(0, 4)
                            .map((weakness, i) => (
                                <li key={i} className="text-sm text-gray-600 flex items-start gap-2">
                                    <span className="text-red-500 font-bold">•</span>
                                    {weakness}
                                </li>
                            ))
                        }
                        {(!results.categoryDetails || Object.values(results.categoryDetails).flatMap(d => d.weaknesses).length === 0) && (
                            <li className="text-sm text-gray-500 italic">No critical weaknesses detected. Keep pushing!</li>
                        )}
                    </ul>
                </div>
            </div>

            {/* Footer */}
            <div className="mt-auto pt-8 border-t border-gray-100 text-center text-xs text-gray-400">
                Generated by AI PrepPulse • Confidential Assessment Report
            </div>
        </div>
    );
});

export default AssessmentReport;
